public class FirstClass {
    public static void Method(){
        integer i=103246; System.debug(i);
        String s='you noob'; System.debug(s);
        Boolean b=true; System.debug(b);
        double doo=1.347882915D; System.debug(doo);
        long l=12987591825453457L; System.debug(l);
        id dd='00300000003T2PGAA0'; System.debug(dd);
        date dat; System.debug(dat);
        datetime dtm; System.debug(dtm);
        time tm; System.debug(tm);
        Object obj=new Firstclass(); System.debug(obj);   
    }
}